# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Interective Learning App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Interective Learning App
  pod 'R.swift'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'

end
